apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mmakagon-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Sombru/IoT.git
    targetRevision: p3_mmakagon
    path: p3/confs/app
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true