Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.hostname = "iot"

  config.vm.network "private_network", ip: "192.168.56.110"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "iot-p2"

	# 1 gig and 1 cpu was not enought even for k3s
    vb.memory = 2048 
    vb.cpus = 2

    vb.gui = false
  end

  config.vm.synced_folder ".", "/home/vagrant/project"

  config.vm.provision "shell", path: "scripts/install_k3s.sh"
  config.vm.provision "shell", path: "scripts/install_nerdctl.sh"
  config.vm.provision "shell", path: "scripts/build.sh"
  config.vm.provision "shell", path: "scripts/deploy.sh"

end