Vagrant.configure("2") do |config|
  config.vm.define "pkosturaS" do |server|
	server.vm.box = "ubuntu/jammy64"
	server.vm.hostname = "pkosturaS"
	server.vm.network "private_network", ip: "192.168.56.110"

	server.vm.provider "virtualbox" do |vb|
		vb.name = "pkosturaS"

		# 1 gig and 1 cpu was not enought even for k3s
		vb.memory = 2048 
		vb.cpus = 2

		vb.gui = false
	end

	server.vm.synced_folder ".", "/home/vagrant/project"

	server.vm.provision "shell", path: "scripts/install_k3s.sh"
	server.vm.provision "shell", path: "scripts/install_nerdctl.sh"
	server.vm.provision "shell", path: "scripts/build.sh"
	server.vm.provision "shell", path: "scripts/deploy.sh"
  end
end