IP_SERVER = "192.168.56.110"
IP_WORKER = "192.168.56.111"

Vagrant.configure("2") do |config|

  config.vm.define "anmakaroS" do |server|
    server.vm.box = "debian/bookworm64"
    server.vm.hostname = "anmakaroS"
    server.vm.network "private_network", ip: IP_SERVER

    server.vm.provider "virtualbox" do |vb|
      vb.name = "anmakaroS"
      vb.memory = 2048
      vb.cpus = 2
    end

    server.vm.provision "shell", path: "scripts/server.sh", args: [IP_SERVER]
  end

  config.vm.define "anmakaroSW" do |worker|
    worker.vm.box = "debian/bookworm64"
    worker.vm.hostname = "anmakaroSW"
    worker.vm.network "private_network", ip: IP_WORKER

    worker.vm.provider "virtualbox" do |vb|
      vb.name = "anmakaroSW"
      vb.memory = 2048
      vb.cpus = 2
    end

    # worker.vm.provision will run AFTER the server has already booted
    # (Vagrant brings up machines in the order they are defined),
    # so the token file below will exist by the time this runs.
    worker.vm.provision "shell", path: "scripts/worker.sh", args: [IP_SERVER, IP_WORKER]
  end

end